<a href="https://colab.research.google.com/github/maps-05/portfolio/blob/main/ArrayOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. IMPORTING AND CREATING ARRAYS

In [ ]:
import numpy as np

In [ ]:
first_array = np.array([1, 2, 3, 4, 5])
print("A one-dimensional array:")
print(first_array)

A one-dimensional array:
[1 2 3 4 5]


In [ ]:
first_array.dtype

dtype('int64')

In [ ]:
second_array = np.array([[1, 2, 3], [4, 5, 6]])
print("A two-dimensional array:")
print(second_array)

A two-dimensional array:
[[1 2 3]
 [4 5 6]]


2. BASIC ARRAY OPERATIONS

In [ ]:
array1 = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
array2 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

# Element-wise Addition
addition = array1 + array2
print("Using element-wise Addition:")
print(addition)

Using element-wise Addition:
[[ 3  7 11]
 [15 19 23]
 [27 31 35]]


In [ ]:
# Element-wise Subtraction
subtraction = array1 - array2
print("Using element-wise Subtraction:")
print(subtraction)

Using element-wise Subtraction:
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


In [ ]:
# Element-wise Multiplication
multiplication = array1 * array2
print("Using element-wise Multiplication:")
print(multiplication)

Using element-wise Multiplication:
[[  2  12  30]
 [ 56  90 132]
 [182 240 306]]


In [ ]:
# Element-wise Division
division = array1 / array2
print("Using element-wise Division:")
print(division)

Using element-wise Division:
[[0.5        0.75       0.83333333]
 [0.875      0.9        0.91666667]
 [0.92857143 0.9375     0.94444444]]


In [ ]:
# Extracting Specific Elements
spec_element = array1[1, 2]
print("Using specific element (array1[1, 2]):", spec_element)

Using specific element (array1[1, 2]): 11


In [ ]:
# Extracting a Subarray
subarray = array1[:2, :2]
print("Using subarray (first two rows and columns):")
print(subarray)

Using subarray (first two rows and columns):
[[1 3]
 [7 9]]


3. RESHAPING AND TRANSPOSING ARRAYS

In [ ]:
third_array = np.arange(1, 10)
print("Original Array:")
print(third_array)

Original Array:
[1 2 3 4 5 6 7 8 9]


In [ ]:
reshaped_array = third_array.reshape(3, 3)
print("Reshaped 3x3 Array:")
print(reshaped_array)

Reshaped 3x3 Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
transposed_array = reshaped_array.transpose()
print("Transposed Array:")
print(transposed_array)

Transposed Array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


4. ACTIVITY

In [ ]:
# Importing Numpy

import numpy as np

In [ ]:
# Creating a 3by3 Numpy array

my_array = np.arange(1, 10).reshape(3, 3)
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Finding the sum of the array

array_sum = np.sum(my_array)
print(f"The sum of this array is {array_sum}.")

The sum of this array is 45.


In [ ]:
# Finding the mean of the array

array_mean = np.mean(my_array)
print(f"The mean of this array is {array_mean}.")

The mean of this array is 5.0.


In [ ]:
# Finding the standard deviation of the array

array_std = np.std(my_array)
print(f"The standard deviation of this array is {array_std}.")

The standard deviation of this array is 2.581988897471611.


In [ ]:
# Extracting the subarray

subarray = [row[:2] for row in my_array[:2]]
print(subarray)

[array([1, 2]), array([4, 5])]
